### ISSUE TITLE
Character encoding issues in translated YML files

### ISSUE THREAD

**Issue by zeke** [electron/electron-i18n#12]
The English file doesn't have issues:

https://github.com/electron/electron-i18n/blob/a3256e88cacf589a82427c25ea274801740ffce1/content/en/api/api-descriptions.yml#L715-L720

The Czech file does:

https://github.com/electron/electron-i18n/blob/a3256e88cacf589a82427c25ea274801740ffce1/content/cs-CZ/api/api-descriptions.yml#L505-L509

My editor is displaying some unrecognized characters:

<img width="756" alt="screen shot 2017-06-13 at 2 16 02 pm" src="https://user-images.githubusercontent.com/2289/27105027-e72d7a22-5042-11e7-94e0-257b5ef18c63.png">

And here's the error the [js-yaml](https://github.com/nodeca/js-yaml) parser is throwing:

```
  1) electron-i18n translated content preserves YAML formatting of API descriptions:
     end of the stream or a document separator is expected at line 505, column 18:
                     
                     ^
  Error
      at generateError (node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
      at throwError (node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
      at readDocument (node_modules/js-yaml/lib/js-yaml/loader.js:1513:5)
      at loadDocuments (node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
      at load (node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
      at Object.safeLoad (node_modules/js-yaml/lib/js-yaml/loader.js:1584:10)
      at getKeys (test/index.js:39:26)
      at locales.forEach.locale (test/index.js:50:42)
      at Array.forEach (native)
      at Context.it (test/index.js:48:15)
```

**Comment by zeke** [comment]
Also the Czech file still has the unwanted `---` at the top.

**Comment by zeke** [comment]
Crowdin fixed this. 👍
